import { type product, type user } from '../models/app.models';

export const usersDatabase: user[] = [
  {
    userName: 'Kari Laxman',
    userEmail: 'kalaxman@hasedIn.com',
    userPasswordHash: 'password',
    userProfilePicture: '',
    role: 'user',
    userProducts: [],
    userPhoneNumber: '',
    userCart: [],
    userPurchases: [],
    userProductSales: [],
    userProductTrades: [],
    userProductWishList: [],
    userProductReview: [],
    userNotifications: [],
    userSettings: [],
    userCreatedAt: '',
    userUpdatedAt: '',
  },
  {
    userName: 'Kari',
    userEmail: 'k',
    userPasswordHash: 'pa',
    userProfilePicture: '',
    role: 'user',
    userProducts: [],
    userPhoneNumber: '',
    userCart: [],
    userPurchases: [],
    userProductSales: [],
    userProductTrades: [],
    userProductWishList: [],
    userProductReview: [],
    userNotifications: [],
    userSettings: [],
    userCreatedAt: '',
    userUpdatedAt: '',
  },
  {
    userName: 'Kari Ramani',
    userEmail: 'ramani@hasedIn.com',
    userPasswordHash: 'password',
    userProfilePicture: '',
    role: 'user',
    userProducts: [],
    userPhoneNumber: '',
    userCart: [],
    userPurchases: [],
    userProductSales: [],
    userProductTrades: [],
    userProductWishList: [],
    userProductReview: [],
    userNotifications: [],
    userSettings: [],
    userCreatedAt: '',
    userUpdatedAt: '',
  },
  {
    userName: 'Kari Hardeep',
    userEmail: 'hardeep@hasedIn.com',
    userPasswordHash: 'password',
    userProfilePicture: '',
    role: 'user',
    userProducts: [],
    userPhoneNumber: '',
    userCart: [],
    userPurchases: [],
    userProductSales: [],
    userProductTrades: [],
    userProductWishList: [],
    userProductReview: [],
    userNotifications: [],
    userSettings: [],
    userCreatedAt: '',
    userUpdatedAt: '',
  },
  {
    userName: 'Pavan Sagi',
    userEmail: 'pavansagi@hasedIn.com',
    userPasswordHash: 'password',
    userProfilePicture: '',
    role: 'user',
    userProducts: [],
    userPhoneNumber: '',
    userCart: [],
    userPurchases: [],
    userProductSales: [],
    userProductTrades: [],
    userProductWishList: [],
    userProductReview: [],
    userNotifications: [],
    userSettings: [],
    userCreatedAt: '',
    userUpdatedAt: '',
  },
];

export const products: product[] = [
  {
    productId: '1',
    productName: 'Watch',
    productOwner: usersDatabase[0].userEmail,
    productDescription:
      'TIMEWEAR Analog Day Date Functioning Stainless Steel Chain Watch for Men',
    productPrice: 250,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Electronics',
    productDateAdded: '2024-08-04T14:30:00Z',
  },
  {
    productId: '12',
    productName: 'Shoes',
    productOwner: usersDatabase[0].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 2100,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Sports',
    productDateAdded: '2023-12-15T04:30:00Z',
  },
  {
    productId: '13',
    productName: 'Badminton Racket',
    productOwner: usersDatabase[1].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 2200,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Sports',
    productDateAdded: '2024-01-04T14:30:00Z',
  },
  {
    productId: '10',
    productName: 'Hoddy',
    productOwner: usersDatabase[1].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 220,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Clothing',
    productDateAdded: '2024-07-04T14:30:00Z',
  },
  {
    productId: '23',
    productName: 'Pant',
    productOwner: usersDatabase[2].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 2980,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Clothing',
    productDateAdded: '2021-08-14T14:30:00Z',
  },
  {
    productId: '33',
    productName: 'Table',
    productOwner: usersDatabase[2].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 120,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Home',
    productDateAdded: '2024-01-01T14:30:00Z',
  },
  {
    productId: '321',
    productName: 'Computer systems',
    productOwner: usersDatabase[3].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 1230,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Books',
    productDateAdded: '2024-04-11T14:30:00Z',
  },
  {
    productId: '145',
    productName: 'IPhone 15',
    productOwner: usersDatabase[3].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 2240,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Electronics',
    productDateAdded: '2020-08-02T14:30:00Z',
  },
  {
    productId: '50',
    productName: 'Chair',
    productOwner: usersDatabase[0].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 252410,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Home',
    productDateAdded: '2024-08-04T14:30:00Z',
  },
  {
    productId: '90',
    productName: 'IWatch',
    productOwner: usersDatabase[0].userEmail,
    productDescription: 'Stylish watch',
    productPrice: 4500,
    // productImage: "src\assets\watch-olves.jpg",
    productCondition: 'New',
    productCategory: 'Electronics',
    productDateAdded: '2024-08-05T14:30:00Z',
  },
];

export const productCategories = [
  'all',
  'Books',
  'Home',
  'Electronics',
  'Clothing',
  'Sports',
];
